import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/ui/home/Navbar";
import Footer from "@/app/ui/home/Footer";


export const metadata: Metadata = {
  title: "Clever Karma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="relative overflow-hidden">

          {children}
        </main>


      </body>
    </html>
  );
}
