// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAIFF6RFUocZKsWEyc7wetA8imEYcTUiY',
    appId: '1:957908399416:web:5126151c900ce5b64e7dcd',
    messagingSenderId: '957908399416',
    projectId: 'clever-karma-152f3',
    authDomain: 'clever-karma-152f3.firebaseapp.com',
    storageBucket: 'clever-karma-152f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPRwvbtTPWoZoMuZiXMwePaJHsbIuwzf8',
    appId: '1:957908399416:android:fca275ca28ea021d4e7dcd',
    messagingSenderId: '957908399416',
    projectId: 'clever-karma-152f3',
    storageBucket: 'clever-karma-152f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKa72lWI9g51n2oMvBz-NQL0iAtphCcuU',
    appId: '1:957908399416:ios:f0cc7e96c0bfeeef4e7dcd',
    messagingSenderId: '957908399416',
    projectId: 'clever-karma-152f3',
    storageBucket: 'clever-karma-152f3.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKa72lWI9g51n2oMvBz-NQL0iAtphCcuU',
    appId: '1:957908399416:ios:f0cc7e96c0bfeeef4e7dcd',
    messagingSenderId: '957908399416',
    projectId: 'clever-karma-152f3',
    storageBucket: 'clever-karma-152f3.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAIFF6RFUocZKsWEyc7wetA8imEYcTUiY',
    appId: '1:957908399416:web:434e6d0357d350de4e7dcd',
    messagingSenderId: '957908399416',
    projectId: 'clever-karma-152f3',
    authDomain: 'clever-karma-152f3.firebaseapp.com',
    storageBucket: 'clever-karma-152f3.appspot.com',
  );

}